### ISSUE TITLE
python pkgs for QtPy in Bullseye

### ISSUE THREAD

**Issue by cerizza** [FRIBDAQ/SpecTcl#8]
* From a first quick test, it seems some of the packages have been removed or replaced (httplib2 as one example)
* When trying to run SpecTcl with Xamine here is the message

```
Sourceing the config file:
Sourced
Building channel maps
ERROR in cling::CIFactory::createCI(): cannot extract standard library include paths!
Invoking:
  LC_ALL=C x86_64-linux-gnu-g++-8   -xc++ -E -v /dev/null 2>&1 | sed -n -e '/^.include/,${' -e '/^ \/.*++/p' -e '}'
Results was:
With exit code 0
```

Building stack maps

* ROOT 6.18-004 doesn't compile from src it breaks with the following error
[ 58%] Building CXX object interpreter/llvm/src/tools/clang/lib/Sema/CMakeFiles/clangSema.dir/SemaAttr.cpp.o
```
CMake Error at DAVIX-stamp/DAVIX-download-RelWithDebInfo.cmake:49 (message):
  Command failed: 1

   '/usr/bin/cmake' '-Dmake=' '-Dconfig=' '-P' '/usr/opt/root/root_build/builtins/davix/DAVIX-prefix/src/DAVIX-stamp/DAVIX-download-RelWithDebInfo-impl.cmake'

  See also

    /usr/opt/root/root_build/builtins/davix/DAVIX-prefix/src/DAVIX-stamp/DAVIX-download-*.log


gmake[2]: *** [builtins/davix/CMakeFiles/DAVIX.dir/build.make:110: builtins/davix/DAVIX-prefix/src/DAVIX-stamp/DAVIX-download] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:7433: builtins/davix/CMakeFiles/DAVIX.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
```

**Comment by rfoxkendo** [comment]
Nothing to do with channel maps everything to do with root initialization.  I think a newer version of root works however 6.26.04

**Comment by rfoxkendo** [comment]
just missing python3-httplib2 package from our bullseye container.

**Comment by rfoxkendo** [comment]
1. Using Root 6.26.04 fixes any root error message -after rebuilding it under the current bullseye container.
2. Adding the python3-httplib2 package to the bullseye container makes the import test for CutiePie pass under that container image.

**Comment by rfoxkendo** [comment]
All SpecTcl tests now pass....but there are missing libraries in the run time imports for CutiePie
seems like there;'s a need to be more explicit in adding to libraries.

**Comment by rfoxkendo** [comment]
Still some buster issue that I'm not smart enough to figure out in python/sip files etc:

When starting qtpi:

Traceback (most recent call last):
  File "Main.py", line 16, in <module>
    from GUI import MainWindow
  File "./Script/GUI.py", line 51, in <module>
    import CPyConverter as cpy
ValueError: PyCapsule_GetPointer called with incorrect name

Assigning to Giordano to finish off... but this means there's a capsule named differently than what's fetched and could be a .sip error. I"m going to try this on buster as well.



I got a few import failures fixed adding appropriate libraries which I'll commit/merge now but...

**Comment by cerizza** [comment]
Possible solution
https://stackoverflow.com/questions/55794101/valueerrorpycapsule-getpointer-called-with-incorrect-name-with-from-pyqt5-qtwe

**Comment by rfoxkendo** [comment]
Yeah this is really a procdedural error... if the underlying package changes then the interface (sip) must be regenerated as well.... 
While this is 'closed' I'm leaving it open so that the answer is here.
